# Overrides for Production AWS
replicaCount: 3
image:
  tag: "4c9802b"
ingress:
  host: "api.upwind.systems"
  tlsSecretName: "status-api-tls-prod"
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"
env:
  appEnv: "production"
  databaseUrlSecret:
    name: "status-api-db"
    key: "url"
  deployEventTokenSecret:
    name: "status-api-deploy-event-token"
    key: "token"
