{{- if not .Values.rollout.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  progressDeadlineSeconds: {{ .Values.progressDeadlineSeconds }}
  strategy:
    {{ toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{ toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: APP_ENV
              value: {{ .Values.env.appEnv | quote }}
            - name: REDIS_HOST
              value: {{ .Values.env.redisHost | quote }}
            {{- if .Values.database.localPostgres.enabled }}
            - name: DATABASE_URL
              value: {{ printf "postgresql+psycopg://%s:%s@%s-postgres:%v/%s" .Values.database.localPostgres.auth.username .Values.database.localPostgres.auth.password .Release.Name .Values.database.localPostgres.service.port .Values.database.localPostgres.auth.database | quote }}
            {{- else if .Values.env.databaseUrlSecret.name }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.databaseUrlSecret.name | quote }}
                  key: {{ .Values.env.databaseUrlSecret.key | quote }}
                  optional: false
            {{- else if .Values.env.databaseUrl }}
            - name: DATABASE_URL
              value: {{ .Values.env.databaseUrl | quote }}
            {{- end }}
            {{- if .Values.env.deployEventTokenSecret.name }}
            - name: DEPLOY_EVENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.deployEventTokenSecret.name | quote }}
                  key: {{ .Values.env.deployEventTokenSecret.key | quote }}
                  optional: true
            {{- end }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            {{ toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{ toYaml .Values.readinessProbe | nindent 12 }}
{{- end }}
