apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-secrets-aws
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/northlift/infrastructure-lab.git
    targetRevision: main
    path: gitops/secrets
  destination:
    name: aws-eks-prod
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
