apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: status-api-lab
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/northlift/infrastructure-lab.git
    targetRevision: main
    path: helm/status-api
    helm:
      releaseName: status-api-lab
      valueFiles:
        - values-prod.yaml
        - values-homelab-override.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
