#!/bin/bash
set -euo pipefail

APP_DIR="/home/adminsetup/infrastructure-lab"
SERVICE_NAME="status-api.service"
ENV_FILE="${APP_DIR}/.env"
HEALTH_URL="http://localhost:8000/health"
LOCK_FILE="/tmp/deploy-status-api.lock"

log() { echo "[$(date '+%H:%M:%S')] $*"; }

cleanup() { rm -f "$LOCK_FILE"; }
trap cleanup EXIT

# Prevent concurrent deployments
if ! ( set -o noclobber; echo $$ > "$LOCK_FILE" ) 2>/dev/null; then
  log "Deployment already running (lock file: $LOCK_FILE)"
  exit 1
fi

log "Starting Deployment..."
log "Scope: EC2/systemd deployment only. Kubernetes workloads are managed by ArgoCD."

cd "$APP_DIR"
log "Updating code from origin/main..."
git fetch origin main --prune

if [ -n "$(git status --porcelain)" ]; then
  log "Working tree is not clean (uncommitted changes or untracked files). Aborting."
  exit 1
fi

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$CURRENT_BRANCH" != "main" ]; then
  log "Switching to main branch..."
  git checkout main
fi

if ! git merge --ff-only origin/main; then
  log "Fast-forward merge failed; manual intervention required"
  exit 1
fi

SHORT_SHA=$(git rev-parse --short HEAD)
log "Writing .env for SHA: $SHORT_SHA"

# Write minimal env file for watchdog and container image tag
cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy.sh — DO NOT EDIT
# Commit: ${SHORT_SHA}
WATCHDOG_IMAGE=ghcr.io/northlift/status-api:${SHORT_SHA}
WATCHDOG_PORT=8000
EOF

log "Updating systemd service file..."
sudo cp deploy/status-api.service /etc/systemd/system/
sudo systemctl daemon-reload

log "Restarting service ${SERVICE_NAME}..."
sudo systemctl restart "${SERVICE_NAME}"

log "Checking service health..."
sleep 2

if ! sudo systemctl is-active --quiet "${SERVICE_NAME}"; then
  log "Service ${SERVICE_NAME} is not active after restart"
  sudo systemctl status "${SERVICE_NAME}" --no-pager || true
  exit 1
fi

# Simple HTTP health check (retry up to 10x)
HEALTH_OK=false
for i in {1..10}; do
  if curl -sf "${HEALTH_URL}" > /dev/null 2>&1; then
    log "Health check passed (attempt ${i}/10)"
    HEALTH_OK=true
    break
  fi
  log "… waiting for health (${i}/10)"
  sleep 2
done

if [ "${HEALTH_OK}" != "true" ]; then
  log "Health endpoint did not become ready after 20 seconds"
  exit 1
fi

log "Deployment complete."
